use crate::config::UnifiedConfig;
use anyhow::Result;

/// Generate OpenAgent Terminal TOML configuration from unified config
pub fn generate_openagent_config(unified: &UnifiedConfig) -> Result<String> {
    let mut sections = Vec::new();

    // Header comment
    sections.push(format!(
        "# OpenAgent Terminal Configuration\n# Generated by openagent-migrate on {}\n# \n# For more options, see: https://github.com/GeneticxCln/OpenAgent-Terminal\n",
        chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
    ));

    // General section
    sections.push("[general]\nlive_config_reload = true".to_string());

    // Window section
    if has_window_config(unified) {
        let mut window_config = Vec::new();

        if let Some(opacity) = unified.window.opacity {
            window_config.push(format!("opacity = {:.2}", opacity));
        }

        if let Some(decorations) = &unified.window.decorations {
            window_config.push(format!("decorations = \"{}\"", decorations));
        }

        if let Some(title) = &unified.window.title {
            window_config.push(format!("title = \"{}\"", escape_string(title)));
        }

        if let Some(padding) = &unified.window.padding {
            if let (Some(x), Some(y)) = (padding.x, padding.y) {
                window_config.push(format!("padding = {{ x = {}, y = {} }}", x, y));
            }
        }

        if !window_config.is_empty() {
            sections.push(format!("[window]\n{}", window_config.join("\n")));
        }
    }

    // Font section
    if has_font_config(unified) {
        let mut font_config = Vec::new();

        if let Some(size) = unified.font.size {
            font_config.push(format!("size = {:.1}", size));
        }

        if let Some(builtin) = unified.font.builtin_box_drawing {
            font_config.push(format!("builtin_box_drawing = {}", builtin));
        }

        sections.push(format!("[font]\n{}", font_config.join("\n")));

        // Font faces
        if let Some(normal) = &unified.font.normal {
            if let Some(family) = &normal.family {
                sections.push(format!("[font.normal]\nfamily = \"{}\"", escape_string(family)));
                if let Some(style) = &normal.style {
                    sections.push(format!("style = \"{}\"", escape_string(style)));
                }
            }
        }

        // Bold font
        if let Some(bold) = &unified.font.bold {
            if bold.family.is_some() || bold.style.is_some() {
                let mut bold_config = Vec::new();
                if let Some(family) = &bold.family {
                    bold_config.push(format!("family = \"{}\"", escape_string(family)));
                }
                if let Some(style) = &bold.style {
                    bold_config.push(format!("style = \"{}\"", escape_string(style)));
                }
                sections.push(format!("[font.bold]\n{}", bold_config.join("\n")));
            }
        }

        // Italic font
        if let Some(italic) = &unified.font.italic {
            if italic.family.is_some() || italic.style.is_some() {
                let mut italic_config = Vec::new();
                if let Some(family) = &italic.family {
                    italic_config.push(format!("family = \"{}\"", escape_string(family)));
                }
                if let Some(style) = &italic.style {
                    italic_config.push(format!("style = \"{}\"", escape_string(style)));
                }
                sections.push(format!("[font.italic]\n{}", italic_config.join("\n")));
            }
        }
    }

    // Colors section
    if has_color_config(unified) {
        if let Some(primary) = &unified.colors.primary {
            let mut primary_config = Vec::new();
            if let Some(bg) = &primary.background {
                primary_config.push(format!("background = '{}'", bg));
            }
            if let Some(fg) = &primary.foreground {
                primary_config.push(format!("foreground = '{}'", fg));
            }
            if let Some(bright_fg) = &primary.bright_foreground {
                primary_config.push(format!("bright_foreground = '{}'", bright_fg));
            }
            if let Some(dim_fg) = &primary.dim_foreground {
                primary_config.push(format!("dim_foreground = '{}'", dim_fg));
            }

            if !primary_config.is_empty() {
                sections.push(format!("[colors.primary]\n{}", primary_config.join("\n")));
            }
        }

        // Normal colors
        if let Some(normal) = &unified.colors.normal {
            let color_config = generate_color_section(normal, "normal");
            if !color_config.is_empty() {
                sections.push(format!("[colors.normal]\n{}", color_config));
            }
        }

        // Bright colors
        if let Some(bright) = &unified.colors.bright {
            let color_config = generate_bright_color_section(bright, "bright");
            if !color_config.is_empty() {
                sections.push(format!("[colors.bright]\n{}", color_config));
            }
        }

        // Cursor colors
        if let Some(cursor) = &unified.colors.cursor {
            let mut cursor_config = Vec::new();
            if let Some(text) = &cursor.text {
                cursor_config.push(format!("text = '{}'", text));
            }
            if let Some(cursor_color) = &cursor.cursor {
                cursor_config.push(format!("cursor = '{}'", cursor_color));
            }
            if !cursor_config.is_empty() {
                sections.push(format!("[colors.cursor]\n{}", cursor_config.join("\n")));
            }
        }

        // Selection colors
        if let Some(selection) = &unified.colors.selection {
            let mut selection_config = Vec::new();
            if let Some(text) = &selection.text {
                selection_config.push(format!("text = '{}'", text));
            }
            if let Some(bg) = &selection.background {
                selection_config.push(format!("background = '{}'", bg));
            }
            if !selection_config.is_empty() {
                sections.push(format!("[colors.selection]\n{}", selection_config.join("\n")));
            }
        }
    }

    // Terminal section
    if has_terminal_config(unified) {
        // Scrolling
        if let Some(scrolling) = &unified.terminal.scrolling {
            let mut scrolling_config = Vec::new();
            if let Some(history) = scrolling.history {
                scrolling_config.push(format!("history = {}", history));
            }
            if let Some(multiplier) = scrolling.multiplier {
                scrolling_config.push(format!("multiplier = {}", multiplier));
            }
            if !scrolling_config.is_empty() {
                sections.push(format!("[scrolling]\n{}", scrolling_config.join("\n")));
            }
        }

        // Cursor
        if let Some(cursor) = &unified.terminal.cursor {
            let mut cursor_config = Vec::new();

            if let Some(style) = &cursor.style {
                if let Some(shape) = &style.shape {
                    cursor_config.push(format!(
                        "style = {{ shape = \"{}\", blinking = \"{}\" }}",
                        shape,
                        style.blinking.as_deref().unwrap_or("Off")
                    ));
                }
            }

            if let Some(vi_style) = &cursor.vi_mode_style {
                if let Some(shape) = &vi_style.shape {
                    cursor_config.push(format!(
                        "vi_mode_style = {{ shape = \"{}\", blinking = \"{}\" }}",
                        shape,
                        vi_style.blinking.as_deref().unwrap_or("Off")
                    ));
                }
            }

            if let Some(thickness) = cursor.thickness {
                cursor_config.push(format!("thickness = {:.1}", thickness));
            }

            if !cursor_config.is_empty() {
                sections.push(format!("[cursor]\n{}", cursor_config.join("\n")));
            }
        }

        // Selection
        if let Some(selection) = &unified.terminal.selection {
            let mut selection_config = Vec::new();
            if let Some(save_clipboard) = selection.save_to_clipboard {
                selection_config.push(format!("save_to_clipboard = {}", save_clipboard));
            }
            if let Some(semantic_chars) = &selection.semantic_escape_chars {
                selection_config
                    .push(format!("semantic_escape_chars = \"{}\"", escape_string(semantic_chars)));
            }
            if !selection_config.is_empty() {
                sections.push(format!("[selection]\n{}", selection_config.join("\n")));
            }
        }

        // Mouse
        if let Some(mouse) = &unified.terminal.mouse {
            let mut mouse_config = Vec::new();
            if let Some(hide_typing) = mouse.hide_when_typing {
                mouse_config.push(format!("hide_when_typing = {}", hide_typing));
            }
            if !mouse_config.is_empty() {
                sections.push(format!("[mouse]\n{}", mouse_config.join("\n")));
            }
        }
    }

    // Shell section
    if unified.shell.program.is_some() || unified.shell.args.is_some() {
        let mut shell_config = Vec::new();
        if let Some(program) = &unified.shell.program {
            shell_config.push(format!("program = \"{}\"", escape_string(program)));
        }
        if let Some(args) = &unified.shell.args {
            if !args.is_empty() {
                let args_str = args
                    .iter()
                    .map(|arg| format!("\"{}\"", escape_string(arg)))
                    .collect::<Vec<_>>()
                    .join(", ");
                shell_config.push(format!("args = [{}]", args_str));
            }
        }
        if !shell_config.is_empty() {
            sections.push(format!("[terminal.shell]\n{}", shell_config.join("\n")));
        }
    }

    // Key bindings
    if !unified.key_bindings.is_empty() {
        sections.push("# Key bindings".to_string());
        for binding in &unified.key_bindings {
            let mut binding_config = Vec::new();
            binding_config.push(format!("key = \"{}\"", escape_string(&binding.key)));

            if let Some(mods) = &binding.mods {
                if !mods.is_empty() {
                    binding_config.push(format!("mods = \"{}\"", mods.join("|")));
                }
            }

            if let Some(action) = &binding.action {
                binding_config.push(format!("action = \"{}\"", escape_string(action)));
            }

            if let Some(chars) = &binding.chars {
                binding_config.push(format!("chars = \"{}\"", escape_string(chars)));
            }

            sections.push(format!("[[keyboard.bindings]]\n{}", binding_config.join("\n")));
        }
    }

    // Custom/additional settings
    if !unified.custom.is_empty() {
        sections.push("# Additional settings from original configuration".to_string());
        for (key, value) in &unified.custom {
            sections.push(format!("# {}: {}", key, value));
        }
    }

    // Footer with migration info
    sections.push("\n# Migration completed. You may want to:\n# - Review and adjust color schemes\n# - Check font availability on your system\n# - Verify key bindings work as expected\n# - Enable AI features if desired (see example_config.toml)".to_string());

    Ok(sections.join("\n\n"))
}

fn has_window_config(config: &UnifiedConfig) -> bool {
    config.window.opacity.is_some()
        || config.window.decorations.is_some()
        || config.window.title.is_some()
        || config.window.padding.is_some()
}

fn has_font_config(config: &UnifiedConfig) -> bool {
    config.font.size.is_some()
        || config.font.normal.is_some()
        || config.font.bold.is_some()
        || config.font.italic.is_some()
        || config.font.bold_italic.is_some()
        || config.font.builtin_box_drawing.is_some()
}

fn has_color_config(config: &UnifiedConfig) -> bool {
    config.colors.primary.is_some()
        || config.colors.normal.is_some()
        || config.colors.bright.is_some()
        || config.colors.cursor.is_some()
        || config.colors.selection.is_some()
}

fn has_terminal_config(config: &UnifiedConfig) -> bool {
    config.terminal.scrolling.is_some()
        || config.terminal.cursor.is_some()
        || config.terminal.selection.is_some()
        || config.terminal.mouse.is_some()
}

fn generate_color_section(colors: &crate::config::NormalColors, _section_name: &str) -> String {
    let mut color_config = Vec::new();

    if let Some(black) = &colors.black {
        color_config.push(format!("black = '{}'", black));
    }
    if let Some(red) = &colors.red {
        color_config.push(format!("red = '{}'", red));
    }
    if let Some(green) = &colors.green {
        color_config.push(format!("green = '{}'", green));
    }
    if let Some(yellow) = &colors.yellow {
        color_config.push(format!("yellow = '{}'", yellow));
    }
    if let Some(blue) = &colors.blue {
        color_config.push(format!("blue = '{}'", blue));
    }
    if let Some(magenta) = &colors.magenta {
        color_config.push(format!("magenta = '{}'", magenta));
    }
    if let Some(cyan) = &colors.cyan {
        color_config.push(format!("cyan = '{}'", cyan));
    }
    if let Some(white) = &colors.white {
        color_config.push(format!("white = '{}'", white));
    }

    color_config.join("\n")
}

fn generate_bright_color_section(
    colors: &crate::config::BrightColors,
    _section_name: &str,
) -> String {
    let mut color_config = Vec::new();

    if let Some(black) = &colors.black {
        color_config.push(format!("black = '{}'", black));
    }
    if let Some(red) = &colors.red {
        color_config.push(format!("red = '{}'", red));
    }
    if let Some(green) = &colors.green {
        color_config.push(format!("green = '{}'", green));
    }
    if let Some(yellow) = &colors.yellow {
        color_config.push(format!("yellow = '{}'", yellow));
    }
    if let Some(blue) = &colors.blue {
        color_config.push(format!("blue = '{}'", blue));
    }
    if let Some(magenta) = &colors.magenta {
        color_config.push(format!("magenta = '{}'", magenta));
    }
    if let Some(cyan) = &colors.cyan {
        color_config.push(format!("cyan = '{}'", cyan));
    }
    if let Some(white) = &colors.white {
        color_config.push(format!("white = '{}'", white));
    }

    color_config.join("\n")
}

fn escape_string(s: &str) -> String {
    // Basic string escaping for TOML
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::*;

    #[test]
    fn test_generate_basic_config() {
        let mut config = UnifiedConfig::new();
        config.font.size = Some(12.0);
        config.font.normal = Some(FontFaceConfig {
            family: Some("JetBrains Mono".to_string()),
            style: Some("Regular".to_string()),
        });
        config.window.opacity = Some(0.9);

        let result = generate_openagent_config(&config);
        assert!(result.is_ok());

        let toml = result.unwrap();
        assert!(toml.contains("size = 12.0"));
        assert!(toml.contains("opacity = 0.90"));
        assert!(toml.contains("family = \"JetBrains Mono\""));
    }

    #[test]
    fn test_escape_string() {
        assert_eq!(escape_string("simple"), "simple");
        assert_eq!(escape_string("with\"quote"), "with\\\"quote");
        assert_eq!(escape_string("with\\backslash"), "with\\\\backslash");
        assert_eq!(escape_string("with\nnewline"), "with\\nnewline");
    }

    #[test]
    fn test_has_font_config() {
        let mut config = UnifiedConfig::new();
        assert!(!has_font_config(&config));

        config.font.size = Some(12.0);
        assert!(has_font_config(&config));
    }

    #[test]
    fn test_color_section_generation() {
        let colors = crate::config::NormalColors {
            black: Some("#000000".to_string()),
            red: Some("#ff0000".to_string()),
            ..Default::default()
        };

        let section = generate_color_section(&colors, "test");
        assert!(section.contains("black = '#000000'"));
        assert!(section.contains("red = '#ff0000'"));
    }
}
